import React from "react";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  headerContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "90%",
  },
  allNetworksView: {
    flexDirection: "row",
    marginTop: "15%",
    marginLeft: "10%",
    alignItems: "center",
  },
  allNetworksImage: {
    width: 15,
    height: 16,
    marginHorizontal: "2%",
  },
  allNetworksText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#253452",
    marginHorizontal: "2%",
  },
  dropdownImage: {
    width: 20,
    height: 20,
    marginTop: "2%",
  },
  timerImage: {
    alignSelf: "center",
    marginTop: "15%",
  },

  wallet: {
    width: 355,
    height: 169,
    backgroundColor: "#f0f0f0",
    borderRadius: 10,
    padding: 10,
    marginTop: 30,
    alignSelf: "center",
    marginHorizontal: 10,
    marginLeft: 25,
  },
  walletName: {
    fontSize: 13,
    fontWeight: "700",
    color: "#ffffff",
    marginLeft: 15,
    marginTop: 10,
  },
  walletCode: {
    fontSize: 13,
    fontWeight: "400",
    marginLeft: 15,
    color: "#ffffff",
  },
  receiveText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#ffffff",
    position: "absolute",
    top: 25,
    right: 10,
    marginHorizontal: "5%",
  },
  dotContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 10,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#ccc",
    marginHorizontal: 5,
  },
  activeDot: {
    backgroundColor: "#F19220",
  },
  walletImage: {
    width: 200,
    height: 180,
    position: "absolute",
    right: 1,
    resizeMode: "stretch",
    borderRadius: 10,
  },
  walletContentContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  walletBalanceContainer: {
    marginTop: "10%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  yourBalanceText: {
    fontSize: 14,
    fontWeight: "400",
    color: "#ffffff",
    marginLeft: 16,
  },
  balanceText: {
    fontSize: 29,
    fontWeight: "900",
    color: "#ffffff",
    marginLeft: 15,
    marginTop: "-2%",
  },
  modalIconContainer: {
    alignItems: "center",
    justifyContent: "center",
    width: 19,
    height: 25,
    right: 10,
  },
  modalDotImage: {
    width: 3,
    height: 15,
    marginTop: 22,
  },
  currencyContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "87%",
    borderWidth: 1,
    borderColor: "#808BA0",
    height: 95,
    borderRadius: 15,
    alignSelf: "center",
    marginTop: "7%",
    // overflow: "hidden",
  },
  coinNameText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#344567",
  },
  coinNameSubText: {
    fontSize: 11,
    fontWeight: "400",
    color: "#7483A1",
  },
  priceText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#344567",
    textAlign: "right",
  },
  priceSubText: {
    fontSize: 11,
    fontWeight: "400",
    color: "#344567",
    textAlign: "right",
  },
  additionalContent: {
    marginTop: 10,
    padding: 10,
    backgroundColor: "#F4F7FA",
    borderRadius: 15,
    width: "86.2%",
    height: 80,
    alignSelf: "center",
  },
  plusImage: {
    width: 40,
    height: 40,
    right: "5%",
    top: "35%",
  },
  noDataMessage: {
    textAlign: "center",
    fontSize: 24,
    fontWeight: "bold",
    color: "#253452",
  },
  imoprtTokenView: {
    alignItems: "center",
    justifyContent: "center",
    width: "87%",
    backgroundColor: "#F19220",
    height: 45,
    alignSelf: "center",
    borderRadius: 15,
    // top: "-15%",
  },
  importTokenText: {
    textAlign: "center",
    color: "#000000",
    fontSize: 14,
    fontWeight: "700",
  },
  contractAddressText: {},
});
