import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  headerContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "90%",
  },
  coinDetailsParent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  allNetworksView: {
    flexDirection: "row",
    marginTop: "10%",
    marginLeft: "10%",
    alignItems: "center",
  },
  allNetworksImage: {
    width: 15,
    height: 16,
    marginHorizontal: "2%",
  },
  allNetworksText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#253452",
    marginHorizontal: "2%",
  },
  dropdownImage: {
    width: 20,
    height: 20,
    marginTop: "2%",
  },
  coinImageContainer: {
    width: 33,
    height: 35,
    backgroundColor: "#5C80E7",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  coinImage: {
    width: 15,
    height: 22,
  },
  parentView: {
    width: "87%",
    height: "auto",
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#808BA0",
    alignSelf: "center",
    marginTop: "3%",
  },
  headerText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#253452",
    textAlign: "center",
    marginTop: "8%",
  },
  balanceText: {
    color: "#9299A8",
    fontSize: 11,
    fontWeight: "600",
    marginTop: "8%",
    marginRight: "3%",
  },
  inputContainer: {
    marginTop: "5%",
    width: 305,
    height: 67,
    alignSelf: "center",
    borderRadius: 15,
    backgroundColor: "rgba(244, 247, 250, 1)",
    marginBottom: 10,
    alignItems: "flex-start",
  },
  input: {
    width: "80%",
    height: 50,
    fontSize: 15,
    fontWeight: "400",
    paddingHorizontal: 8,
    marginTop: "3%",
    marginLeft: "3%",
    color: "#253452",
  },
  usdPrice: {
    top: "-60%",
    left: "82%",
    fontSize: 16,
    fontWeight: "400",
    color: "#253452",
    textAlign: "center",
  },
  amountRangeView: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    width: "80%",
    alignSelf: "center",
  },
  amountRangeText: {
    fontSize: 10,
    fontWeight: "600",
    color: "#A5ACBC",
  },
  dividerContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: "87%",
    alignSelf: "center",
    marginTop: "5%",
  },
  divider: {
    flex: 1,
    height: 1.5,
    backgroundColor: "#808BA0",
  },
  swapImageContainer: {
    width: 45,
    height: 40,
    borderRadius: 15,
    backgroundColor: "#F2A13F",
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: "3%",
  },
  image: {
    width: 24,
    height: 24,
    marginHorizontal: 10,
  },
  currencyConvertView: {
    width: "80%",
    height: 78,
    alignSelf: "center",
    alignItems: "center",
    marginTop: "8%",
  },
  currencyConverterText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#7483A1",
    marginTop: "2%",
    textAlign: "center",
  },
  importButton: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: "10%",
    width: "87%",
    height: 55,
    alignSelf: "center",
    borderRadius: 10,
    backgroundColor: "#F4F7FA",
    marginBottom: "3%",
  },
  importText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#ffffff",
  },
  alertMessage: {
    fontSize: 12,
    fontWeight: "600",
    color: "#253452",
  },
  languageButton: {
    alignItems: "center",
    justifyContent: "center",
    width: 105,
    height: 40,
    backgroundColor: "#F19220",
    borderRadius: 50,
    marginHorizontal: "2%",
  },
  englishText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#ffffff",
  },
  doneButton: {
    width: "87%",
    height: 55,
    alignSelf: "center",
    // borderColor: "#ffffff",
    // borderWidth: 0.5,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F19220",
    marginTop: "10%",
  },

  disabledButton: {
    backgroundColor: "#F4F7FA",
  },
  disabledText: {
    color: "#979797",
  },
});
