import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  buySellButtonView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '10%',
  },
  languageButton: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '28%',
    height: 34,
    backgroundColor: '#F19220',
    borderRadius: 50,
    marginHorizontal: '2%',
  },
  englishText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#ffffff',
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '90%',
  },
  coinDetailsParent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  allNetworksView: {
    flexDirection: 'row',
    marginTop: '10%',
    marginLeft: '10%',
    alignItems: 'center',
  },
  allNetworksImage: {
    width: 15,
    height: 16,
    marginHorizontal: '2%',
  },
  allNetworksText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#253452',
    marginHorizontal: '2%',
  },
  dropdownImage: {
    width: 20,
    height: 20,
    marginTop: '2%',
  },
  coinImageContainer: {
    width: 33,
    height: 35,
    backgroundColor: '#5C80E7',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  coinImage: {
    width: 32,
    height: 32,
  },
  parentView: {
    width: '87%',
    height: 359,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#808BA0',
    alignSelf: 'center',
    marginTop: '7%',
  },
  headerText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#253452',
    textAlign: 'center',
    marginTop: '8%',
  },
  balanceText: {
    color: '#253452',
    fontSize: 23,
    fontWeight: '400',
    marginTop: '5%',
    marginRight: '3%',
  },
  inputContainer: {
    marginTop: '5%',
    width: 305,
    height: 67,
    alignSelf: 'center',
    borderRadius: 15,
    backgroundColor: 'rgba(244, 247, 250, 1)',
    marginBottom: 10,
    alignItems: 'flex-start',
  },
  input: {
    height: 50,
    fontSize: 15,
    fontWeight: '400',
    paddingHorizontal: 8,
    marginTop: '3%',
    marginLeft: '3%',
    color: '#253452',
  },
  amountRangeView: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    width: '80%',
    alignSelf: 'center',
  },
  amountRangeText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#A5ACBC',
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '87%',
    alignSelf: 'center',
    marginTop: '15%',
  },
  divider: {
    flex: 1,
    height: 1,
    backgroundColor: '#808BA0',
  },
  swapImageContainer: {
    width: 45,
    height: 40,
    borderRadius: 15,
    backgroundColor: '#F2A13F',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: '3%',
  },
  image: {
    width: 24,
    height: 24,
    marginHorizontal: 10,
  },
  currencyConvertView: {
    width: '80%',
    height: 78,
    alignSelf: 'center',
    alignItems: 'center',
    marginTop: '13%',
  },
  currencyConverterText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#7483A1',
    marginTop: '2%',
    textAlign: 'center',
  },
  importButton: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '25%',
    width: '87%',
    height: 55,
    alignSelf: 'center',
    borderRadius: 10,
    backgroundColor: '#F4F7FA',
    marginBottom: '3%',
  },
  importText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#979797',
  },
  alertMessage: {
    fontSize: 12,
    fontWeight: '600',
    color: '#253452',
  },
  languageButton: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 105,
    height: 40,
    backgroundColor: '#F19220',
    borderRadius: 50,
    marginHorizontal: '2%',
  },
  englishText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#ffffff',
  },
  rangeSelectionView: {
    width: 311,
    height: 53,
    borderRadius: 15,
    backgroundColor: '#F4F7FA',
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    marginTop: '5%',
  },
  rangeText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#253452',
  },
  paymentMethodText: {
    marginLeft: '8%',
    marginTop: '10%',
    fontSize: 16,
    fontWeight: '400',
    color: '#253452',
  },
  createWalletView: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '87%',
    height: 53,
    marginTop: '2%',
    alignSelf: 'center',
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#808BA0',
  },
  createWalletImage: {
    alignSelf: 'center',
    width: 34,
    height: 34,
    marginLeft: '10%',
    marginHorizontal: '5%',
  },
  createWalletText: {
    fontSize: 16,
    fontWeight: '400',
    color: '#233452',
    marginLeft: '4%',
  },
  divider: {
    height: '70%',
    width: 1,
    backgroundColor: '#000000',
  },
  forwardIcon: {
    width: 20,
    height: 20,
    marginLeft: '38%',
    marginTop: '1%',
  },
  paymentMethod: {
    marginLeft: '8%',
    marginTop: '1%',
    fontSize: 11,
    fontWeight: '600',
    color: '#9F9FA0',
  },
});
