import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  header: {
    width: "90%",
    flexDirection: "row",
    justifyContent: "space-around",
    marginTop: "5%",
    marginLeft: "-8%",
  },
  backIcon: {
    width: 25,
    height: 25,
  },
  walletText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#253452",
    marginTop: "-1%",
    marginLeft: "-10%",
  },
  recoveryPharseTextContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: "7%",
    width: "80%",
    alignSelf: "center",
  },
  recoveryPhraseText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#253452",
  },
  subText: {
    fontSize: 14,
    fontWeight: "400",
    color: "#9F9FA0",
    textAlign: "center",
    width: "115%",
    marginTop: "4%",
  },
  securityMessageContainer: {
    alignItems: "center",
    alignSelf: "center",
    width: "88%",
    borderWidth: 1,
    borderColor: "#F3AB1D",
    borderRadius: 15,
    height: "12%",
    marginTop: "7%",
    backgroundColor: "#F4F7FA",
  },
  alertImage: {
    width: 38,
    height: 40,
    marginTop: "2%",
  },
  securityText: {
    fontSize: 13,
    fontWeight: "400",
    color: "#000000",
    textAlign: "center",
    width: "85%",
  },
  securityPhraseContainer: {
    alignSelf: "center",
    width: "87%",
    height: "38.5%",
    borderRadius: 15,
    marginTop: "10%",
    backgroundColor: "#F4F7FA",
  },
  securityPhraseTextContainer: {
    flexDirection: "row",
    width: "90%",
    alignSelf: "center",
    justifyContent: "space-between",
    marginTop: "3%",
  },
  countingText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#B7BECD",
    marginHorizontal: "8%",
  },
  namesText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#253452",
  },
  termsConsentContainer: {
    flexDirection: "row",
    width: "85%",
    alignSelf: "center",
    marginTop: "1%",
    marginLeft: "5%",
  },

  copyIcon: {
    justifyContent: "center",
    marginTop: "3%",
    width: "85%",
    alignSelf: "center",
    marginLeft: "155%",
  },
  checkBox: {
    alignSelf: "center",
    marginLeft: "-3%",
    marginHorizontal: "3%",
    // width: "15%",
  },
  consentText: {
    fontSize: 13,
    fontWeight: "400",
    color: "#9F9FA0",
    width: "95%",
  },
  importButton: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: "5%",
    width: "85%",
    height: "6.5%",
    alignSelf: "center",
    borderRadius: 15,
    backgroundColor: "#D5DFEB",
  },
  importText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#979797",
  },
  importButtonEnabled: {
    backgroundColor: "#F19220",
  },
  importTextEnabled: {
    color: "#FFFFFF",
  },
  namesTextContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 10,
  },
});
