export const currencyData = [
  {
    id: "1",
    coinName: "ETH",
    coinNameSubText: "Ether",
    priceText: "0.00",
    priceSubText: "0.000000000",
    additionalContent: [
      { action: "Send", icon: "send.png" },
      { action: "Receive", icon: "receive.png" },
      { action: "Swap", icon: "swap.png" },
      { action: "Chart", icon: "chart.png" },
    ],
    balance: "$51,895.70",
  },
  // {
  //   id: "2",
  //   coinName: "BTC",
  //   coinNameSubText: "Bitcoin",
  //   priceText: "0.00",
  //   priceSubText: "0.000000000",
  //   additionalContent: [
  //     { action: "Send", icon: "send.png" },
  //     { action: "Receive", icon: "receive.png" },
  //     { action: "Swap", icon: "swap.png" },
  //     { action: "Chart", icon: "chart.png" },
  //   ],
  //   balance: "$51,895.70",
  // },
  // {
  //   id: "3",
  //   coinName: "BTC",
  //   coinNameSubText: "Bitcoin",
  //   priceText: "0.00",
  //   priceSubText: "0.000000000",
  //   additionalContent: [
  //     { action: "Send", icon: "send.png" },
  //     { action: "Receive", icon: "receive.png" },
  //     { action: "Swap", icon: "swap.png" },
  //     { action: "Chart", icon: "chart.png" },
  //   ],
  //   balance: "$51,895.70",
  // },
  // {
  //   id: "4",
  //   coinName: "BTC",
  //   coinNameSubText: "Bitcoin",
  //   priceText: "0.00",
  //   priceSubText: "0.000000000",
  //   additionalContent: [
  //     { action: "Send", icon: "send.png" },
  //     { action: "Receive", icon: "receive.png" },
  //     { action: "Swap", icon: "swap.png" },
  //     { action: "Chart", icon: "chart.png" },
  //   ],
  //   balance: "$51,895.70",
  // },
  // {
  //   id: "5",
  //   coinName: "BTC",
  //   coinNameSubText: "Bitcoin",
  //   priceText: "0.00",
  //   priceSubText: "0.000000000",
  //   additionalContent: [
  //     { action: "Send", icon: "send.png" },
  //     { action: "Receive", icon: "receive.png" },
  //     { action: "Swap", icon: "swap.png" },
  //     { action: "Chart", icon: "chart.png" },
  //   ],
  //   balance: "$51,895.70",
  // },
  // {
  //   id: "6",
  //   coinName: "BTC",
  //   coinNameSubText: "Bitcoin",
  //   priceText: "0.00",
  //   priceSubText: "0.000000000",
  //   additionalContent: [
  //     { action: "Send", icon: "send.png" },
  //     { action: "Receive", icon: "receive.png" },
  //     { action: "Swap", icon: "swap.png" },
  //     { action: "Chart", icon: "chart.png" },
  //   ],
  //   balance: "$51,895.70",
  // },
];
